### ISSUE TITLE
bot joins but its does not play the sound

### ISSUE THREAD

**Issue by ShrimantaGarain** [Sattishh/voice-interrupter-discord-bot#2]

**Comment by Sattishh** [comment]
Hey! I know why you're getting this issue. If you see the start.bat, it probably says "FFmpeg not found"

This is because you need to install ``ffmpeg`` (something I forgot to add into the Setup Guide)

How to Install FFmpeg - 

 You need to install this zip file and extract it wherever you want to.
Then go to "edit system environment variables" and add new for Path.

Please watch this video from 2:24 to 5:20
https://youtu.be/Q7GW6v5DnFI?t=144

It will help you understand it with installing ffmpeg. 

After doing the setup, reopen start.bat and it should work!

If it still doesn't work, let me know what error it shows, thanks!

Zip File - https://drive.google.com/file/d/1gaLYSLZQQkR7GL3_GCbq-kEalE5PlHSz/view?usp=sharing

**Comment by ShrimantaGarain** [comment]
i have ffmpeg installed still no sound!

**Comment by Sattishh** [comment]
Can you provide me with the error in the start.bat / screenshot of your start.bat so i can see the error log

**Comment by ShrimantaGarain** [comment]
the bot joins the vc but the bot don't make any sound although the green circle which shows that the bot is talking is visible

cmd output after start.bat is triggered :

C:\Users\shrim\Downloads\Compressed\voice-interrupter-discord-bot-main\voice-interrupter-discord-bot-main>node index.js
NO NEW SOUND INPUTTED. USING DEFAULT ANNOYING SOUND!
Ready to disturb someone.

**Comment by Sattishh** [comment]
Thank you for the reply! I have identified the issue relating to installation. 

To fix this issue, please download the new **[Release](https://github.com/Sattishh/voice-interrupter-discord-bot/releases/tag/v1.1)**.

In this new Release, you will 

need to run `firstinstall.bat` -> `secondinstall.bat` -> `start.bat` 

instead of `install.bat` -> `start.bat`

Join a voice channel and the bot will talk when you talk. If you run into any other issue, just open a new Issue! Thanks
